### ISSUE TITLE
Drivers should be able to cancel carpools

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#1]
Use case: Driver creates a carpool, leaves the page, and some time later needs to cancel the carpool. All passengers and potential passengers should be notified.

- [x] UI
  - [x] A way for the driver to cancel their carpool
  - [x] Confirm that the driver wanted to cancel
- [x] Backend
  - [x] Send emails to the riders

**Comment by iandees** [comment]
From the UX side I'm implementing this with a link that is only visible to the person that created the carpool:

![image](https://cloud.githubusercontent.com/assets/261584/24733996/15c62670-1a49-11e7-80c5-0efd346f2d10.png)

When they click that, they get a confirmation screen:

![image](https://cloud.githubusercontent.com/assets/261584/24734003/258af676-1a49-11e7-9e81-3e94c9a027d1.png)

**Comment by iandees** [comment]
... but the more I think about this, the more I think I want to add a page to hang these carpool-specific things off of, so I'll probably change this implementation here in a bit.

**Comment by agdt3** [comment]
@iandees I'm adding the feature to email riders when a driver cancels the carpool. Is that OK? (I hope I didn't accidentally duplicate your work)

**Comment by iandees** [comment]
Nope, not started yet. I was going to put together a more general emailing system using Mailgun, but I'm happy to take whatever you've got.

**Comment by agdt3** [comment]
I just wrote the function to email users on carpool cancel. You can hook it up to whatever service you'd like via env vars.

**Comment by iandees** [comment]
Sounds good!

**Comment by agdt3** [comment]
Can I get permissions to push a new branch for the PR?

**Comment by iandees** [comment]
@agdt3 you've been invited as a collaborator.

**Comment by iandees** [comment]
I'm going to close this because drivers can cancel their carpools. It can definitely be improved, but let's make tickets for that later.
