### ISSUE TITLE
"Signed in as ."

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#16]
When I log in with a G Suite account, the app doesn't get a 'name' for me (this is a known issue with G Suite accounts). As a result, the UI says "Signed in as ." If we detect this case, we should send the user to the Profile page to fill in a name.
![screen shot 2017-04-16 at 7 51 42 am](https://cloud.githubusercontent.com/assets/2319837/25072006/888659cc-2279-11e7-9238-7cb1c69bea02.png)

**Comment by jillh510** [comment]
I'm still seeing the issue.

**Comment by iandees** [comment]
Looks like I didn't put this change on Heroku. I will do that now.
