### ISSUE TITLE
Allow passenger to cancel interest in a carpool

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#4]
Use case: Passenger inquires about a carpool but decides not to join. Passenger should be able to cancel interest in the carpool, opening the seat for someone else.

**Comment by iandees** [comment]
A passenger that has a ride request can cancel that ride request from the carpool details screen.

I'm going to close this for now, but it might make sense to include a list of carpools the user is a part of (both as a rider and a driver) in their profile or something.
