### ISSUE TITLE
Safari lack of map auto-complete leads to server thinking carpool has no locations

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#43]
Steps to reproduce:
- Was logged in via Facebook, Safari on Mac.
- Had previously requested a ride in someone else's carpool
- Went to "Add a carpool" page, filled in the info. Clicked "Add Carpool"

Result: Internal Server Error

**Comment by iandees** [comment]
https://sentry.io/ragtag/carpools/issues/255378458/
