### ISSUE TITLE
Changing my name in the Profile page doesn't change the "Signed in as" text

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#6]
Steps to reproduce:
Log in with a gmail account. At the top right, the text says "Signed in as Jill Huchital."
Click "Jill Huchital" to get to the Profile page
Type a new name in the "Name" box and click "Update your Profile"
Result: text in the upper right doesn't change.

If I reloaded the page, the text changed.

**Comment by iandees** [comment]
I just fixed this locally (on the ngrok instance). Can you try again?

**Comment by jillh510** [comment]
Fixed
