### ISSUE TITLE
Move "Delete your account" button somewhere less convenient

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#62]
I think users frequently expect the "Submit" button to be at the bottom of a form. Having the "Delete your Account" button in that spot on the Profile page could lead to lots of false clicks (even with the warning note). Can the "Delete" button move somewhere less convenient, like to the right of the "Your Profile" text?

**Comment by iandees** [comment]
:) Yep I noticed this yesterday. It's supposed to be over on the right but I think I screwed up the CSS.

Having it to the right means that it'll be underneath on small screens, though. I might separate it with a bigger heading and some text to make it obvious what's going on.

**Comment by iandees** [comment]
The button and text are in a "well" off to the right side now.
